config/routes.rb
Tarot::Application.routes.draw do
  get "welcome/index"

  root to: 'welcome#index'

  resources :games do
    resources :rounds, :players
  end

  

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :players
  has_many :rounds
  accepts_nested_attributes_for :players
  validates :number_of_players, 
    presence: true#, 
#    value: {minimum: 3, maximum: 5} @todo
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :game
  has_many :player_scores
end

app/models/player_score.rb
class PlayerScore < ActiveRecord::Base
  belongs_to :player
end

app/models/round.rb
class Round < ActiveRecord::Base
  belongs_to :game
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

def index
  @games = Game.all
end

def show
  @game = Game.find(params[:id])
  if params.has_key? 'delete_round'
    round_number = params['delete_round'].to_i
    if round_number > 0 
      @game.players.each do | player |
        score = player.player_scores[round_number]
        score.destroy
      end 
    end
  redirect_to game_path(@game)
  end
end

def new
  @game = Game.new
end

def create
  @game = Game.new(game_params)
  @game.date = Date.today
  @game.number_of_players = 0
  if @game.save
    redirect_to new_game_player_path(@game)
  else
    render text: @game.errors.first
  end
end

def destroy
  @game = Game.find(params[:id])
  @game.destroy
  redirect_to games_path
end

private
  def game_params
    params.require(:game).permit(:location)
  end

end

app/controllers/player_scores_controller.rb
class PlayerScoresController < ApplicationController

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

def new
  @player = Player.new
end

def create
  @game = Game.find(params[:game_id])
  if params[:player]["name"].length > 0
    @player = @game.players.create(params[:player].permit(:name))
    @player.name = @player.name.capitalize
    
    score = PlayerScore.new
    score.score = 0
    @player.player_scores.append score
    @game.number_of_players = @game.number_of_players + 1

    @game.save

    redirect_to new_game_player_path(@game)
  else
    redirect_to game_path(@game)
  end
end

end

app/controllers/rounds_controller.rb
$contracts = { petite: 10,
              pousse: 20,
              garde: 40,
              garde_sans: 80,
              garde_contre: 160 }

def countPoints(startingScoresHash, roundHash)
  points = roundHash[:diff].to_i
  if points >= 0
    points += $contracts[roundHash[:contract].to_sym]
  else
    points -= $contracts[roundHash[:contract].to_sym]
  end

  factor = startingScoresHash.length - 1
  if startingScoresHash.has_key? roundHash[:partner]
    factor -= 2
  end

  finalScoresHash = Hash.new(startingScoresHash)

  startingScoresHash.each do | player_name, score |
    if player_name == roundHash[:lead]
      finalScoresHash[player_name] = score + factor * points
    elsif player_name == roundHash[:partner]
      finalScoresHash[player_name] = score + points
    else
      finalScoresHash[player_name] = score - points
    end
  end

  finalScoresHash
end

class RoundsController < ApplicationController

def new
  @round = Round.new
  @game = Game.find(params[:game_id])
  @players = @game.players
end

def validate_players(round, players_list)
  #valid = players_list.include? round['lead']
  #if valid && round[:partner].length > 0
  #  valid = players_list.include? round[:partner] 
  #end
  valid = true
end

def create
  @game = Game.find(params[:game_id])
  params[:round][:contract] = $contracts.key(params[:round][:contract].to_i)
  params[:round][:lead] = params[:round][:lead].capitalize

  if params[:round].has_key? :partner
    params[:round][:partner] = params[:round][:partner].capitalize
  end
  
  if validate_players(params[:round], @game.players)
    @round = @game.rounds.create(params[:round].permit(:lead, :partner, :diff, :contract))

    currentScores = Hash.new(@game.players.length)
    @game.players.each do |player|
      currentScores[player.name] = player.player_scores.last.score
    end
    updatedScores = countPoints(currentScores,params[:round])

    @game.players.each do |player|
      new_score = PlayerScore.new
      new_score.score = updatedScores[player.name]
      player.player_scores.append new_score
    end

    redirect_to game_path(@game)
  else
    @round = Round.new(params[:round].permit(:lead, :partner, :diff, :contract))
    @round.errors.add('lead','player name invalid')
    render 'new'
  end

end

def index
  @rounds = Round.all
  render text: @rounds.length
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/player_scores_helper.rb
module PlayerScoresHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/games/index.html.erb
<div id="top" class="header">
  <div class="vert-text">
    <h1>Tarot Games</h1>
    <h3>Welcome to our Tarot game score tracker</h3>
    <%= link_to 'New game', new_game_path, class:"btn btn-default btn-lg" %>
  </div>
</div>
<hr>
<div id="gameslist" class="services">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4 text-center">
         <h3>Previous games</h3>
         <hr>
      </div>
    </div>

    <div class="row">
      <% @games.each do |game| %>
        <div class="col-md-3 text-center">
          <div class="game-item">
            <i class="service-icon"><%= game.date %></i>
            <h4><%= game.location %></h4>
            <%= link_to 'Show', game_path(game), class:"btn btn-default btn-sm" %>
            <%= link_to 'Delete', game_path(game),
                method: :delete, data: { confirm: 'Are you sure?' },
                class:"btn btn-default btn-sm" %>
            <% game.players.each do |player| %>
              <p><%= player.name %></p>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/games/new.html.erb
<h1>New game of Tarot</h1>

<%= form_for :game, url: games_path do |f| %>
  <p>
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back to list of games', games_path %>

app/views/games/show.html.erb
<p>
This is a tarot game taking place in <%= @game.location %> on <%= @game.date %>.
</p>

<p>
Today there are <%= pluralize(@game.number_of_players, "player") %>.
<% if @game.number_of_players < 3 %>
  Time to add players, otherwise what's the point? You need at least three. <%= link_to 'Click here to add players.', new_game_player_path(@game) %><br>
<% end %>
</p>

<h1>Scores</h1>

<% if @game.number_of_players > 0 %>

  <table border="1" cellpadding="3" cellspacing="0">
    <tr>
      <td>Player name</td>
      <% round_number = 0 %>
      <% @game.players.first.player_scores.each do |score| %>
        <td>Round #<%= round_number %><br>
        <% round_number += 1 %>
      <% end %>
    </tr>
    <% @game.players.each do |player| %>
      <tr>
        <td><%= player.name %></td>
        <% player.player_scores.each do | score | %>
          <td><%= score.score %></td>
        <% end %>
      </tr>
    <% end %>
  </table>

  <%= link_to 'New round', new_game_round_path(@game) %><br>
  <%= link_to 'Delete last round', game_path(@game, delete_round: round_number-1) unless round_number == 0 %><br>

<% else %>
  <p>No players registered in this game</p>
<% end %>

<%= link_to 'Back to list of games', games_path %>

<h1>Rounds</h1>
<table border="1" cellpadding="3" cellspacing="0">
  <tr>
    <td>Round</td>
    <td>Points</td>
    <td>Lead player</td>
    <td>Contract</td>
    <td>Partner if any</td>
  </tr>
  <% round_number = 1 %>
  <% @game.rounds.each do |round| %>
    <tr>
      <td>#<%= round_number %></td>
      <td><%= round.diff %></td>
      <td><%= round.lead %></td>
      <td><%= round.contract %></td>
      <td><%= round.partner %></td>
    </tr>
    <% round_number += 1 %>
  <% end %>
</table>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Home", root_path, :class => 'brand' %>
<ul class="nav">
  <li> <%= link_to('List of games', games_path) %> </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tarot</title>
    <meta name="description" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <!-- Side Menu -->
    <a id="menu-toggle" href="#" class="btn btn-primary btn-lg toggle"><i class="fa fa-reorder">Menu</i></a>
    <div id="sidebar-wrapper">
      <ul class="sidebar-nav">
        <a id="menu-close" href="#" class="btn btn-default btn-lg pull-right toggle"><i class="fa fa-times">Close</i></a>
        <li><%= link_to 'Home', games_path %></li>
        <% if (defined? @games) == nil %>
          <% @games = Game.all %>
        <% end %>
        <% @games.each do |game| %>
          <li>Game on<%= link_to game.date, game_path(game) %></li>
        <% end %>
        <% if (defined? @game) != nil %>
          <li><%= link_to 'Back to the game', game_path(@game) %></li> 
        <% end %>
      </ul>
    </div>
    <!-- /Side Menu -->

    <main role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>

    <!-- Bootstrap core JavaScript -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="js/jquery.js"></script>
    <script src="js/bootstrap.js"></script>

    <!-- Custom JavaScript for the Side Menu and Smooth Scrolling - Put in a custom JavaScript file to clean this up -->
    <script>
        $("#menu-close").click(function(e) {
            e.preventDefault();
            $("#sidebar-wrapper").toggleClass("active");
        });
    </script>
    <script>
        $("#menu-toggle").click(function(e) {
            e.preventDefault();
            $("#sidebar-wrapper").toggleClass("active");
        });
    </script>
    <script>
      $(function() {
        $('a[href*=#]:not([href=#])').click(function() {
          if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') 
            || location.hostname == this.hostname) {

            var target = $(this.hash);
            target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
            if (target.length) {
              $('html,body').animate({
                scrollTop: target.offset().top
              }, 1000);
              return false;
            }
          }
        });
      });
    </script>


        </div>
      </div>
    </main>
  </body>
</html>

app/views/players/new.html.erb
<h1>Add a player (leave empty when done)</h1>
<%= form_for :player, url: game_players_path do | f | %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/rounds/index.html.erb
<h1>Rounds</h1>
<table>
  <% @rounds.each do |round| %>
    <tr>
      <td><%= round.lead.name %></td>
      <td><%= round.contract %></td>
      <td><%= round.partner.name %></td>
      <td><%= round.diff %></td>
    </tr>
  <% end %>
</table>

app/views/rounds/new.html.erb
<h1>New round</h1>

<%= form_for :round, url: game_rounds_path do |f| %>

<% if @round.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@round.errors.count, "error") %> prohibited this round from being saved:</h2>
    <ul>
      <% @round.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<table>
  <tr>
    <td><%= f.label :lead %></td>
    <td><%= f.collection_select :lead, @players, :name, :name %></td>
  </tr>
  <tr>
    <td><%= f.label :contract %></td>
    <td><%= f.select :contract, options_for_select($contracts) %></td>
  </tr>
  <% if @players.size > 3 %>
  <tr>
    <td><%= f.label :partner %></td>
    <td><%= f.collection_select :partner, @players, :name, :name, include_blank: :true %></td>
  </tr>
  <% end %>
  <tr>
    <td><%= f.label :diff %></td>
    <td><%= f.text_field :diff %></td>
  </tr>
</table>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/rounds/show.html.erb
<p>Lead: <%= @round.lead.name %></p>
<p>Partner: <%= @round.partner.name %></p>
<p>Contract: <%= @round.contract %></p>
<p>Diff: <%= @round.diff %> </p>

app/views/welcome/index.html.erb
<h1>Let's play tarot!</h1>
<%= link_to "Tarot game tracker", controller: "games" %>
<p>Find me in app/views/welcome/index.html.erb</p>